apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
  namespace: brennonloveless-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: brennonloveless-com
  name: deployment-updater
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-deployment
  namespace: brennonloveless-com
subjects:
- kind: ServiceAccount
  name: deploy
roleRef:
  kind: Role
  name: deployment-updater
  apiGroup: rbac.authorization.k8s.io
