name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.102.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Compress
        run: tar cvvfz -C public brennonloveless.com-${{ github.ref_name }}.tgz public/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: brennonloveless.com-${{ github.ref_name }}.tgz
